"""create initial tables

Revision ID: a8a911a1a59c
Revises: 
Create Date: 2026-07-09 20:50:58.773662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a911a1a59c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address used for login'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's display name"),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='Argon2-hashed password'),
    sa.Column('role', sa.Enum('TEAM_MEMBER', 'MANAGER', name='userrole'), nullable=False, comment='User role: TEAM_MEMBER or MANAGER'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete flag — inactive users cannot login'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique project/category name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional project description'),
    sa.Column('color_hex', sa.String(length=7), nullable=False, comment='Hex color for chart visualization (e.g. #6366f1)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete flag — inactive projects hidden from dropdown'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='Manager who created this project'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('weekly_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Author of this report'),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Project/category this report is for'),
    sa.Column('week_start', sa.Date(), nullable=False, comment='Monday of the reporting week'),
    sa.Column('week_end', sa.Date(), nullable=False, comment='Sunday of the reporting week'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'LATE', name='reportstatus'), nullable=False, comment='Report lifecycle state: DRAFT, SUBMITTED, or LATE'),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True, comment='Hours worked during this week (optional, 0-168)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes or links'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='Timestamp when report was submitted (null if draft)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours_worked IS NULL OR hours_worked >= 0', name='ck_hours_non_negative'),
    sa.CheckConstraint('week_end > week_start', name='ck_week_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'week_start', name='uq_user_project_week')
    )
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_project_id'), 'weekly_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_status'), 'weekly_reports', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_start'), 'weekly_reports', ['week_start'], unique=False)
    op.create_table('report_blockers',
    sa.Column('report_id', sa.Uuid(), nullable=False, comment='Parent report this blocker belongs to'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the blocker or challenge'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='Whether this blocker has been resolved'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment="Preserves user's ordering within the form"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['weekly_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_blockers_id'), 'report_blockers', ['id'], unique=False)
    op.create_index(op.f('ix_report_blockers_report_id'), 'report_blockers', ['report_id'], unique=False)
    op.create_table('report_tasks',
    sa.Column('report_id', sa.Uuid(), nullable=False, comment='Parent report this task belongs to'),
    sa.Column('task_type', sa.Enum('COMPLETED', 'PLANNED', name='tasktype'), nullable=False, comment='COMPLETED (done this week) or PLANNED (next week)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Task description text'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment="Preserves user's ordering within the form"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['weekly_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_tasks_id'), 'report_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_report_tasks_report_id'), 'report_tasks', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_tasks_report_id'), table_name='report_tasks')
    op.drop_index(op.f('ix_report_tasks_id'), table_name='report_tasks')
    op.drop_table('report_tasks')
    op.drop_index(op.f('ix_report_blockers_report_id'), table_name='report_blockers')
    op.drop_index(op.f('ix_report_blockers_id'), table_name='report_blockers')
    op.drop_table('report_blockers')
    op.drop_index(op.f('ix_weekly_reports_week_start'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_status'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_project_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
